/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bank_management_system;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author Sneha
 */
public class accountbalance extends javax.swing.JFrame {

    /**
     * Creates new form accountbalance
     */
    public accountbalance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        account = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        submitbt = new javax.swing.JButton();
        balance = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        showbalance = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ADD ACCOUNT BALANCE ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 230, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Account Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Enter amount");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        account.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 190, -1));

        amount.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 190, -1));

        submitbt.setBackground(new java.awt.Color(51, 204, 0));
        submitbt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitbt.setText("DEPOSIT");
        submitbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtActionPerformed(evt);
            }
        });
        getContentPane().add(submitbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        balance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        balance.setText("0000");
        getContentPane().add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 90, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("<BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        showbalance.setBackground(new java.awt.Color(255, 204, 102));
        showbalance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showbalance.setText("current balance");
        showbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbalanceActionPerformed(evt);
            }
        });
        getContentPane().add(showbalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank_management_system/deposit_bms.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtActionPerformed
        // TODO add your handling code here:
        String accnum=account.getText();
        String Amount =amount.getText();
        int AmountInt=Integer.parseInt(Amount);
        try{
            java.sql.Connection conn =java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/banking","root","" );
            
            String sql2 = "UPDATE account SET accountbalance = accountbalance + ? WHERE accountnumber = ?";

            PreparedStatement ptmt = conn.prepareStatement(sql2);
            ptmt.setInt(1, AmountInt);
            ptmt.setString(2,accnum);
            ptmt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Money has been Deposited");

        conn.close();
            

            
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_submitbtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dashboard obj=new dashboard();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void showbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbalanceActionPerformed
        // TODO add your handling code here:
        try {
        // Establish database connection
        java.sql.Connection conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/banking", "root", "");

        // Prepare SQL statement to retrieve account balance based on account number
        String sql = "SELECT accountbalance FROM account WHERE accountnumber = ?";
        PreparedStatement ptst = conn.prepareStatement(sql);
        ptst.setString(1, account.getText()); // Set the account number from the text field
        ResultSet rs = ptst.executeQuery();

        if (rs.next()) {
            // If a record is found, update the balance label with the retrieved balance
            balance.setText(rs.getString("accountbalance"));
        } else {
            // If no record is found for the entered account number, display a message indicating the account was not found
            balance.setText(""); // Clear the balance label
            JOptionPane.showMessageDialog(null, "Account not found");
        }

        // Close the database connection
        conn.close();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_showbalanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accountbalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accountbalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accountbalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accountbalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accountbalance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account;
    private javax.swing.JTextField amount;
    private javax.swing.JLabel balance;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton showbalance;
    private javax.swing.JButton submitbt;
    // End of variables declaration//GEN-END:variables
}
