/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bank_management_system;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Sneha
 */
public class Billpayment extends javax.swing.JFrame {

    /**
     * Creates new form Billpayment
     */
    public Billpayment() {
        initComponents();
        currentdatetime();
    }
    
    public void currentdatetime(){
        
        DateTimeFormatter dtf= DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        LocalDateTime now=LocalDateTime.now();
        datetime.setText(dtf.format(now));
        
        
        
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        datetime = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        accnum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        min = new javax.swing.JTextField();
        max = new javax.swing.JTextField();
        viewbalancebt = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        acbalance = new javax.swing.JTextField();
        billername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 51, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("PAY BILLS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        datetime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        datetime.setText("DATE");
        getContentPane().add(datetime, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("BILL TYPE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "ELECTRICITY", "PHONE ", "AC", "GAS", " " }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 192, -1));

        jButton2.setBackground(new java.awt.Color(51, 204, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("VIEW LIMITS");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("ACCOUNT NUMBER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        accnum.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(accnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 200, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("AMOUNT");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        amount.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 200, -1));

        jButton4.setBackground(new java.awt.Color(51, 204, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("PAY");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, -1, -1));

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("CANCEL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("DBank: Making payments a breeze!");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        jLabel7.setText("MIN");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, -1));

        jLabel8.setText("MAX");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));

        min.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 117, -1));

        max.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(max, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 117, -1));

        viewbalancebt.setBackground(new java.awt.Color(51, 204, 0));
        viewbalancebt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewbalancebt.setForeground(new java.awt.Color(255, 255, 255));
        viewbalancebt.setText("VIEW BALANCE");
        viewbalancebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbalancebtActionPerformed(evt);
            }
        });
        getContentPane().add(viewbalancebt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("ACCOUNT BALANCE ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        acbalance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        acbalance.setText("0000");
        getContentPane().add(acbalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 90, -1));

        billername.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(billername, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 192, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank_management_system/paybills_bms.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        min.setText("PKR/=01");
        max.setText("PKR/=50,000");
        
        
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
       String selectedValue =(String) jComboBox1.getSelectedItem();
       billername.setText(selectedValue);
        
        
        
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void viewbalancebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbalancebtActionPerformed
        // TODO add your handling code here:
         try{
            java.sql.Connection conn =java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/banking","root","" );
            String sql="select accountbalance from account where accountnumber=?";
            PreparedStatement ptst= conn.prepareStatement(sql);
            ptst.setString(1, accnum.getText());
            ResultSet rs=ptst.executeQuery();
            
            if(rs.next()){
                acbalance.setText(rs.getString("accountbalance"));
            }
            else{
            acbalance.setText(rs.getString(""));
            JOptionPane.showMessageDialog(null,"Account not found");
            

            }
            conn.close();
          
            
            
         }catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
         }
        
        
    }//GEN-LAST:event_viewbalancebtActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            java.sql.Connection conn =java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/banking","root","" );
            String amnt=amount.getText();
            int amntInt=Integer.parseInt(amnt);
            String billerName=billername.getText();
            
            String sql="select accountbalance from account where accountnumber=?";
            PreparedStatement ptst= conn.prepareStatement(sql);
            ptst.setString(1, accnum.getText());
            ResultSet rs=ptst.executeQuery();
            if(rs.next()){
                acbalance.setText(rs.getString("accountbalance"));
                String accbalance =rs.getString("accountbalance");
                int  accbalanceInt=Integer.parseInt(accbalance);
                if(accbalanceInt>=amntInt){
                    int leftover=accbalanceInt-amntInt;
                    
                    String sql1="update account SET accountbalance =?";
                    PreparedStatement ptmt=conn.prepareStatement(sql1);
                    ptmt.setInt(1, leftover);
                    ptmt.execute();
                    
                    String sql2="insert into paybills values(?,?,?)";
                    PreparedStatement pts=conn.prepareStatement(sql2);
                    pts.setString(1, billername.getText());
                    pts.setString(2, amount.getText());
                    pts.setString(3, datetime.getText());
                    pts.executeUpdate();
                    JOptionPane.showMessageDialog(null,"YOUR "+billerName+" BILL OF AMOUNT  "+amnt+" HAS BEEN PAID ");
                 
                }
                 else{
                JOptionPane.showMessageDialog(null,"your account balance is insufficient");
                     }
            }
            else{
                acbalance.setText("");
            }
           
   
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error while establishing the connection");
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dashboard obj=new dashboard();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dashboard obj=new dashboard();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billpayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acbalance;
    private javax.swing.JTextField accnum;
    private javax.swing.JTextField amount;
    private javax.swing.JTextField billername;
    private javax.swing.JLabel datetime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField max;
    private javax.swing.JTextField min;
    private javax.swing.JButton viewbalancebt;
    // End of variables declaration//GEN-END:variables
}
