/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bank_management_system;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
/**
 *
 * @author Sneha
 */
public class Instantpayment extends javax.swing.JFrame {

    /**
     * Creates new form Instantpayment
     */
    public Instantpayment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        account = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        purpose = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        mobile = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        note = new javax.swing.JTextField();
        bankname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("INSTANT PAYMENT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("SELECT BANK");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("ACCOUNT NUMBER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("AMOUNT");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("PURPOSE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("PAYEE EMAIL");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("PAYEE MOBILE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, 20));

        jButton1.setText("<BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        account.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 150, 200, -1));

        amount.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 207, 200, -1));

        purpose.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(purpose, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 265, 200, -1));

        email.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 319, 200, -1));

        mobile.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 375, 200, -1));

        jButton2.setBackground(new java.awt.Color(51, 204, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("PAY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 471, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Axis Bank", "Bank of Baroda", "City Union Bank", "DBank", "Indian Bank", "Karur Vysaya Bank", "State Bank of India " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 93, 201, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("NOTE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 50, 20));

        note.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(note, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 442, 200, -1));

        bankname.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 53, 201, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bank_management_system/instantpayment_bms.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            java.sql.Connection conn =java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/banking","root","" );
            String amnt=amount.getText();
            String bank = bankname.getText();
        
        // Prepare the SQL query to fetch account balance based on account number
        String sql2 = "SELECT accountbalance FROM account WHERE accountnumber = ?";
        PreparedStatement ptstmt = conn.prepareStatement(sql2);
        
        // Set the value of the account number parameter
        ptstmt.setString(1, account.getText());
        
        // Execute the query and retrieve the results
        ResultSet rs = ptstmt.executeQuery();
        
        // If the query returns a result
        if (rs.next()) {
            // Get the account balance from the result set
            String accbalance = rs.getString("accountbalance");
            
            // Convert the account balance to an integer
            int accbalanceInt = Integer.parseInt(accbalance);
            int amntInt = Integer.parseInt(amnt);
            int leftover = accbalanceInt - amntInt;

            String sql3 = "UPDATE account SET accountbalance = ? WHERE accountnumber = ?";
            PreparedStatement pt = conn.prepareCall(sql3);
            pt.setInt(1, leftover);
            pt.setString(2, account.getText());
            pt.execute();

            // Prepare the SQL query to insert payment details into the instantpayment table
            String sql = "INSERT INTO instantpayment (bankname, account, amount, purpose, email, phone, note) VALUES (?, ?, ?, ?, ?, ?, ?)";
            
            // Create a PreparedStatement to execute the SQL insert query
            PreparedStatement ptst = conn.prepareStatement(sql);
            
            // Set the parameters for the insert query
            ptst.setString(1, bank);
            ptst.setString(2, account.getText());
            ptst.setString(3, amount.getText());
            ptst.setString(4, purpose.getText());
            ptst.setString(5, email.getText());
            ptst.setString(6, mobile.getText());
            ptst.setString(7, note.getText());
            
            // Execute the insert query
            ptst.executeUpdate();

            // Display a success message
            JOptionPane.showMessageDialog(null, "Amount has been transferred successfully");
            
            // Close the database connection
            conn.close();

                
            }
            
            
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String sv=jComboBox1.getSelectedItem().toString();
        bankname.setText(sv);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dashboard obj=new dashboard();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Instantpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Instantpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Instantpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Instantpayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Instantpayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account;
    private javax.swing.JTextField amount;
    private javax.swing.JTextField bankname;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField note;
    private javax.swing.JTextField purpose;
    // End of variables declaration//GEN-END:variables
}
